amqp:
  admin:
    auto-create: true
  host: localhost
  port: 5672
  username: adm_videos
  password: 123456

keycloak:
  realm: test
  host: http://test:8443

logging:
  level:
    ROOT: info

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}

server:
  port: 8080
  undertow:
    threads:
      worker: 24
      io: 2