logging:
  level:
    ROOT: info

mysql:
  username: root
  password: 123456
  schema: adm_videos
  url: localhost:${mysql.port}

server:
  port: 8080
  undertow:
    threads:
      worker: 24
      io: 2