version: '3.7'

services:
  app:
    container_name: adm_videos_app
    #    image: lucastumeleiro/codeflix-admin-catalogo-videos-java:latest
    build:
      context: ../../
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    env_file:
      - .env.local
    ports:
      - 8080:8080
    networks:
      - adm_videos_network
      - adm_videos_services

networks:
  adm_videos_network:
  adm_videos_services:
    external: true

#  docker-compose up -d
#  docker-compose --profile up -d
#  docker logs -f adm_videos_app
#
#  docker-compose --profile app stop
#  docker-compose --profile app rm