name: CI-CD - Pipeline Catalogo-admin

on:
  push:
    branches:
      - "main"
    paths:
      - "catalogo-admin/**"
  workflow_dispatch: # Habilita o gatilho manual através da interface do Github Actions

env:
  IMAGE_NAME: lucastumeleiro/codeflix-admin-catalogo-videos-java

jobs:
  build:
    name: Build runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"

      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b

      - name: Make gradlew executable
        run: chmod +x ./catalogo-admin/gradlew

      - name: Build da aplicação
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: clean build -x test
          build-root-directory: ./catalogo-admin

      - name: Set BUILD_TAG
        working-directory: ./catalogo-admin
        run: |
          echo BUILD_TAG=$(echo ${{ github.head_ref || github.ref_name }} | sed "s,/,_,g")-${{ github.run_number }} >> $GITHUB_ENV

      - name: Print BUILD_TAG defined
        run: |
          echo "Branch     ---> ${{ github.head_ref || github.ref_name }}"
          echo "Run number ---> ${{ github.run_number }}"
          echo "Tag        ---> ${{ env.BUILD_TAG }}"

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build & push da imagem do docker
        uses: docker/build-push-action@v3
        with:
          context: ./catalogo-admin
          push: true
          build-args: VERSION=${{ env.BUILD_TAG }}
          tags: ${{ env.IMAGE_NAME }}:${{ env.BUILD_TAG }}
