name: CI Pipeline Catalogo-admin

on:
  push:
    branches:
      - "main/**"
    paths:
      - "catalogo-admin/**"
  workflow_dispatch: # Habilita o gatilho manual através da interface do Github Actions

jobs:
  tests:
    name: Tests runner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK@17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "adopt"
      - name: Make gradlew executable
        working-directory: ./catalogo-admin
        run: chmod +x ./gradlew
      - name: Run application tests
        working-directory: ./catalogo-admin
        run: ./gradlew test
